WebUyg-main/WebUyg-main/Final Ödevi/Final-Ödevi/Vize-Ödevi/Controllers/MarketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vize;

namespace Vize_Ödevi.Controllers
{
    public class MarketController : Controller  //Veri üzerinde yacapımız işlemler için ayrı Contoller'lar oluşturduk
    {

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Listele()  //Listeleme için Listele işlemi oluşturduk ve gerekli kodları yazdık.
        {
            using (var session = NhibernateHelper.OpenSession())
            {
                var Marketler = session.Query<Models.Market>().ToList();
                return View(Marketler);
            }

        }
        public IActionResult Yeni()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Yeni(Models.Market markt)   //Yeni kayıt eklemek için oluşturduğumuz Razor View için gerekli kodları ekledik.
        {

            using (var session = NhibernateHelper.OpenSession())
            {
                var market = new Models.Market();
                market.urunAd = markt.urunAd;
                market.tedarikciId = markt.tedarikciId;
                market.alisFiyat = markt.alisFiyat;
                market.satisFiyat = markt.satisFiyat;
                session.SaveOrUpdate(markt);
                session.Flush();
            }
            return RedirectToAction("Listele");
        }

        public IActionResult Detay(int id) //Listemizdeki verinin detayını görmek için detay adında işlem yaptırdık.
        {
            using (var session = NhibernateHelper.OpenSession())
            {
                var r = session.Query<Models.Market>().FirstOrDefault(x => x.Id == id);
                return View(r);

            }
        }


        public IActionResult Guncelle(int id)
        {
            using (var session = NhibernateHelper.OpenSession())
            {
                var r = session.Query<Models.Market>().FirstOrDefault(x => x.Id == id);
                return View(r);
            }
        }

        [HttpPost]  //Listemizdeki herhangi bir veri üzerinde güncelleme yapabilmek için güncelle işlemi oluşturduktan sonra gerekli kodları ekledik.

        public IActionResult Guncelle(Models.Market Mrkt)
        {
            using (var session = NhibernateHelper.OpenSession())
            {
                var r = session.Query<Models.Market>().FirstOrDefault(x => x.Id == Mrkt.Id);
                r.urunAd = Mrkt.urunAd;
                r.tedarikciId = Mrkt.tedarikciId;
                r.alisFiyat = Mrkt.alisFiyat;
                r.satisFiyat = Mrkt.satisFiyat;
                session.SaveOrUpdate(r);
                session.Flush();
            }

            return RedirectToAction("Listele");
        }


        public IActionResult Sil(int id) //Listeden Veri silebilmek için Sil işlemi oluşturduk.
        {
            using (var session = NhibernateHelper.OpenSession())
            {
                var r = session.Query<Models.Market>().FirstOrDefault(x => x.Id == id);
                return View(r);


            }

        }

        [HttpPost]

        public IActionResult Sil(Models.Market Mrkt)
        {
            using (var session = NhibernateHelper.OpenSession())
            {
                var r = session.Query<Models.Market>().FirstOrDefault(x => x.Id == Mrkt.Id);
                session.Delete(r);
                session.Flush();


            }
            return RedirectToAction("Listele");


        }




    }
}

WebUyg-main/WebUyg-main/Final Ödevi/Final-Ödevi/Vize-Ödevi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Market</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body {
            background: beige;
        }

        nav {
            width: 100%;
            background: white;
            padding: 20px 0;
        }

            nav ul {
                list-style: none;
                text-align: center;
            }

                nav ul li {
                    display: inline-block;
                }

                    nav ul li a {
                        display: block;
                        padding: 20px;
                        text-decoration: none;
                        color: blue;
                        font-weight: 600;
                        font-size: 13pt;
                        font-family: Verdana, Geneva, Tahoma, sans-serif;
                        text-transform: uppercase;
                        margin: 0 10px;
                    }

                        nav ul li a:hover {
                            border-bottom: 3px solid red;
                            color: #5b616e;
                        }

        .tablo {
            width: 80%;
            border: 1px solid #fff;
            text-align: center;
            margin-left: auto;
            margin-right: auto;
            margin-top: 5%;
        }

            .tablo table {
                margin-left: auto;
                margin-right: auto;
                color: #fff;
                text-align: center;
            }

                .tablo table td {
                    width: 400px;
                }

        .table-basliklar {
            font-size: 15pt;
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Final Ödevi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="" asp-area="" asp-controller="Market" asp-action="listele">Ürünler</a>
                        </li>
                        <li class="nav-item">
                            <a class="" asp-area="" asp-controller="Musteriler" asp-action="listele">Müsteriler</a>
                        </li>
                        <li class="nav-item">
                            <a class="" asp-area="" asp-controller="Siparisler" asp-action="listele">Siparişler</a>
                        </li>
                        <li class="nav-item">
                            <a class="" asp-area="" asp-controller="Tedarikci" asp-action="listele">Tedarikçiler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>